# Generated by Django 5.1.2 on 2024-11-05 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productApp', '0002_product_stripe_price_id_product_stripe_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='parent_order_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('FULFILLED', 'Fulfilled')], default='PENDING', max_length=10),
        ),
    ]
