# Generated by Django 5.1.2 on 2024-11-09 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productApp', '0009_order_seat_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Accepted', 'ACCEPTED'), ('Cooking', 'COOKING'), ('Ready', 'READY'), ('waiting', 'WAITING')], default='Accepted', max_length=10),
        ),
    ]
