# Generated by Django 5.1.2 on 2024-11-09 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productApp', '0010_order_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
